# -*- coding: utf-8 -*-
"""Взаимодействие с оболочкой системы.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d9RyfRtsYwkfbqBBjmpIcA7meeEzwx_w
"""

!ls
!which python
!mkdir new_folder
!rmdir new_folder