# -*- coding: utf-8 -*-
"""Работа с файлами.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11MZCSU1XaFxtiO7uPRIjXrVI-X0kQTHq
"""

import os

# Создание и запись в файл
with open("example.txt", "w") as f:
  f.write("Первая строка\n")
  f.write("Вторая строка\n")

# Чтение файла
with open("example.txt", "r") as f:
  content = f.read()
  print("Содержимое файла:\n", content)

# Проверка существования файла
print("Файл существует:", os.path.exists("example.txt"))

# Удаление файла
os.remove("example.txt")
print("Файл удален.")