# -*- coding: utf-8 -*-
"""Работа с Google Drive в Google Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EUBlIv_5xS0H8h2KXJxyn5wcqHjrIq3E
"""

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive

from google.colab import drive
drive.mount('/content/drive')
# Запись текста в файл
file_path = "/content/drive/MyDrive/my_text_file.txt"
with open(file_path, "w") as f:
f.write("Это тестовый файл, сохраненный в Google Drive.\n")
f.write("Вторая строка текста.")
print("Файл успешно сохранен в Google Drive.")
# Чтение файла
with open(file_path, "r") as f:
content = f.read()
print("Содержимое файла:\n", content)
# Создание CSV вручную
students = [
["Иванов И.И.", 20, "ИВТ-101"],
["Петров П.П.", 22, "ИВТ-102"],
["Сидорова А.А.", 21, "ИВТ-103"]
]
csv_path = "/content/drive/MyDrive/students.csv"
with open(csv_path, "w") as f:
for student in students:
f.write(",".join(map(str, student)) + "\n")
print("Файл students.csv успешно сохранен в Google Drive.")